<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="a-PC" name="Login Test" tests="2" failures="1" timestamp="15 May 2016 08:26:37 GMT" time="44.171" errors="0">
  <testcase name="doLoginTest" time="0.007" classname="com.qtpselenium.zoho.project.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- doLoginTest -->
  <testcase name="doLoginTest" time="41.93" classname="com.qtpselenium.zoho.project.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Login Test Failed.">
      <![CDATA[java.lang.AssertionError: Login Test Failed.
	at com.qtpselenium.zoho.project.base.BaseTest.reportFailure(BaseTest.java:205)
	at com.qtpselenium.zoho.project.testcases.LoginTest.doLoginTest(LoginTest.java:49)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- doLoginTest -->
</testsuite> <!-- Login Test -->
